# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerretScan < Formula
  desc "Find and redact sensitive data before it leaks — PII, secrets, credit cards, metadata"
  homepage "https://github.com/awslabs/ferret-scan"
  version "2.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.2.0/ferret-scan_2.2.0_darwin_amd64"
      sha256 "23ae92abffa7e573c39586f1677d9e8e59c756edf9b906964ca8e062504208bf"

      define_method(:install) do
        bin.install "ferret-scan_2.2.0_darwin_amd64" => "ferret-scan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.2.0/ferret-scan_2.2.0_darwin_arm64"
      sha256 "96093c8ed313b5fc2d04e7fd76a87de888654043e376b3e2d20246b68378305a"

      define_method(:install) do
        bin.install "ferret-scan_2.2.0_darwin_arm64" => "ferret-scan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.2.0/ferret-scan_2.2.0_linux_amd64"
      sha256 "4847ef5bb93ac900142252e47af280c4a60518db28eed2217e4389d2d4bbd74f"
      define_method(:install) do
        bin.install "ferret-scan_2.2.0_linux_amd64" => "ferret-scan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.2.0/ferret-scan_2.2.0_linux_arm64"
      sha256 "5d2f7e822f72a0482f07988992471b6da415aebb042b8495417ce71500519484"
      define_method(:install) do
        bin.install "ferret-scan_2.2.0_linux_arm64" => "ferret-scan"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ferret-scan --version")
    (testpath / "test.txt").write "card 5500-0000-0000-0004\n"
    output = shell_output("#{bin}/ferret-scan --file #{testpath}/test.txt 2>&1")
    assert_match "creditcard", output
  end
end
