# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FerretScan < Formula
  desc "Find and redact sensitive data before it leaks — PII, secrets, credit cards, metadata"
  homepage "https://github.com/awslabs/ferret-scan"
  version "2.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.3.2/ferret-scan_2.3.2_darwin_amd64"
      sha256 "e4df3df9e3a9d3d1358ec58f58b1bbe7a573bc17d95b94e9d7362a959a39f539"

      define_method(:install) do
        bin.install "ferret-scan_2.3.2_darwin_amd64" => "ferret-scan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.3.2/ferret-scan_2.3.2_darwin_arm64"
      sha256 "808fc46d20296cb12f8f6fbc89e0920bb4a45953a9f010b4aa876b720b488108"

      define_method(:install) do
        bin.install "ferret-scan_2.3.2_darwin_arm64" => "ferret-scan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.3.2/ferret-scan_2.3.2_linux_amd64"
      sha256 "992220e9a34da5b203d14d7c2e7afcb86d3cdd8d7a72de025f4cf331cd9dd3fc"
      define_method(:install) do
        bin.install "ferret-scan_2.3.2_linux_amd64" => "ferret-scan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awslabs/ferret-scan/releases/download/v2.3.2/ferret-scan_2.3.2_linux_arm64"
      sha256 "e05e03bbee00fbe72b64b4c8dba4d9fc3b01267f82700e42555da59272bf2098"
      define_method(:install) do
        bin.install "ferret-scan_2.3.2_linux_arm64" => "ferret-scan"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ferret-scan --version")
    (testpath / "test.txt").write "card 5500-0000-0000-0004\n"
    output = shell_output("#{bin}/ferret-scan --file #{testpath}/test.txt 2>&1")
    assert_match "creditcard", output
  end
end
