# GoReleaser v2 configuration for ferret-scan
version: 2

project_name: ferret-scan

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ferret-scan-cli
    main: ./cmd/main.go
    binary: ferret-scan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X ferret-scan/internal/version.Version={{.Version}}
      - -X ferret-scan/internal/version.GitCommit={{.Commit}}
      - -X ferret-scan/internal/version.BuildDate={{.Date}}

# Note: Web UI functionality is now integrated into the main ferret-scan binary
# Use: ferret-scan --web to start web server mode

archives:
  - id: binaries
    formats: [binary]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    ids:
      - ferret-scan-cli

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
  groups:
    - title: 🚀 Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 🐛 Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: ⚡ Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 📦 Code Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 🛠 Build System
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 4
    - title: Others
      order: 999

# GitHub releases
release:
  github:
    owner: awslabs
    name: ferret-scan
  # Ensure release is created even if some steps fail
  draft: false
  prerelease: auto
  # Replace existing release if it exists
  replace_existing_draft: true
  # Archives and checksums are automatically included by GoReleaser
  # No need to specify extra_files for standard artifacts

  header: |
    ## Ferret Scan {{ .Tag }}

    Advanced sensitive data detection and redaction tool for securing your codebase.

    ### What's Changed

  footer: |

    ### 🚀 Quick Installation

    #### Recommended: Install from PyPI
    ```bash
    pip install ferret-scan
    ```

    #### Alternative: Download Binary
    Download the binary for your platform from the assets below if you prefer not to use pip.

    ### 📦 Available Binaries
    Choose the binary that matches your system:
    - **Linux AMD64**: `ferret-scan_{{ .Tag }}_linux_amd64`
    - **Linux ARM64**: `ferret-scan_{{ .Tag }}_linux_arm64`
    - **macOS AMD64 (Intel)**: `ferret-scan_{{ .Tag }}_darwin_amd64`
    - **macOS ARM64 (Apple Silicon)**: `ferret-scan_{{ .Tag }}_darwin_arm64`
    - **Windows AMD64**: `ferret-scan_{{ .Tag }}_windows_amd64.exe`
    - **Windows ARM64**: `ferret-scan_{{ .Tag }}_windows_arm64.exe`
    - **Checksums**: `checksums.txt` - Verify your download integrity

    ### 📖 Documentation
    - [Installation Guide](https://github.com/awslabs/ferret-scan/blob/main/docs/INSTALLATION.md)
    - [Pre-commit Integration](https://github.com/awslabs/ferret-scan/blob/main/docs/PRE_COMMIT_INTEGRATION.md)
    - [Configuration Guide](https://github.com/awslabs/ferret-scan/blob/main/docs/configuration.md)

    **Full Changelog**: https://github.com/awslabs/ferret-scan/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker builds disabled - focusing on binary releases only
