# GoReleaser v2 configuration for ferret-scan
version: 2

project_name: ferret-scan

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ferret-scan-cli
    main: ./cmd/main.go
    binary: ferret-scan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X ferret-scan/internal/version.Version={{.Version}}
      - -X ferret-scan/internal/version.GitCommit={{.Commit}}
      - -X ferret-scan/internal/version.BuildDate={{.Date}}

# Note: Web UI functionality is now integrated into the main ferret-scan binary
# Use: ferret-scan --web to start web server mode

archives:
  - id: binaries
    formats: [binary]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    ids:
      - ferret-scan-cli

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
  groups:
    - title: 🚀 Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 🐛 Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: ⚡ Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 📦 Code Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: 🛠 Build System
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 4
    - title: Others
      order: 999

# GitHub releases
release:
  github:
    owner: awslabs
    name: ferret-scan
  # Ensure release is created even if some steps fail
  draft: false
  prerelease: auto
  # Replace existing release if it exists
  replace_existing_draft: true
  # Archives and checksums are automatically included by GoReleaser
  # No need to specify extra_files for standard artifacts

  header: |
    ## Ferret Scan {{ .Tag }}

    Advanced sensitive data detection and redaction tool for securing your codebase.

    ### What's Changed

  footer: |

    ### 🚀 Quick Installation

    Download the binary for your platform from the assets below, then follow the installation steps.

    #### Linux/macOS Installation
    ```bash
    # Download the binary for your platform (example for Linux amd64)
    # From GitHub releases, download: ferret-scan_{{ .Tag }}_linux_amd64

    # Make it executable and handle macOS security if needed
    chmod +x ferret-scan_{{ .Tag }}_linux_amd64

    # macOS only: Remove quarantine attribute
    xattr -d com.apple.quarantine ferret-scan_{{ .Tag }}_linux_amd64

    # Rename and install system-wide
    sudo mv ferret-scan_{{ .Tag }}_linux_amd64 /usr/local/bin/ferret-scan

    # Verify installation
    ferret-scan --version
    ```

    **⚠️ macOS Security Note**: If macOS blocks execution with "cannot be opened because it is from an unidentified developer", run:
    ```bash
    xattr -d com.apple.quarantine ferret-scan_{{ .Tag }}_darwin_amd64
    ```
    Only use this command for executables from trusted sources.

    #### Windows Installation
    ```powershell
    # Download the binary: ferret-scan_{{ .Tag }}_windows_amd64.exe

    # Rename to ferret-scan.exe
    Rename-Item ferret-scan_{{ .Tag }}_windows_amd64.exe ferret-scan.exe

    # Move to a directory in your PATH (example: C:\Program Files\ferret-scan\)
    # Or add the current directory to your PATH

    # Verify installation
    ferret-scan --version
    ```

    ### 📦 Available Binaries
    Choose the binary that matches your system:
    - **Linux AMD64**: `ferret-scan_{{ .Tag }}_linux_amd64`
    - **Linux ARM64**: `ferret-scan_{{ .Tag }}_linux_arm64`
    - **macOS AMD64 (Intel)**: `ferret-scan_{{ .Tag }}_darwin_amd64`
    - **macOS ARM64 (Apple Silicon)**: `ferret-scan_{{ .Tag }}_darwin_arm64`
    - **Windows AMD64**: `ferret-scan_{{ .Tag }}_windows_amd64.exe`
    - **Windows ARM64**: `ferret-scan_{{ .Tag }}_windows_arm64.exe`
    - **Checksums**: `checksums.txt` - Verify your download integrity

    ### 📖 Documentation
    - [Installation Guide](https://github.com/awslabs/ferret-scan/blob/main/docs/INSTALLATION.md)
    - [Pre-commit Integration](https://github.com/awslabs/ferret-scan/blob/main/docs/PRE_COMMIT_INTEGRATION.md)
    - [Configuration Guide](https://github.com/awslabs/ferret-scan/blob/main/docs/configuration.md)

    **Full Changelog**: https://github.com/awslabs/ferret-scan/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker builds disabled - focusing on binary releases only
