// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package scorecorpus

import (
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/awslabs/ferret-scan/v2/internal/config"
)

// Timing and complexity, for the corpus AND for the scorer itself.
//
// Two separate risks, and the second is the one usually forgotten:
//
//  1. The PRODUCT can go quadratic. This repo has shipped O(n^2) scanning (12 of 13
//     validators on dense single-line input) and O(m*n) redaction (78s on 1MB).
//  2. The GATE can go quadratic, and then it gets deleted for being slow. The
//     scorer's own matching loop is O(labels * matches) per case; that is fine while
//     both are small and must be proven, not assumed.
//
// A wall-clock assertion is deliberately NOT used as the gate: measured spread on a
// loaded laptop was over 4x run to run, which is a flake generator. The gate is
// GROWTH-based (does doubling the input roughly double the work) with an explicit
// vacuity floor, because 3 of this repo's 18 existing complexity targets were once
// no-ops that measured nothing.

// growthCase builds a document with n labelled values on n lines.
func growthCase(n int) Case {
	var b strings.Builder
	labels := make([]Label, 0, n)
	// Three distinct SSNs cycled, so no line repeats a value (TestValueOccursOnce's
	// invariant) and the scorer cannot shortcut on identical text.
	vals := []string{"130-07-5728", "214-89-6712", "301-45-7788"}
	b.WriteString("employee_ssn,dept\n")
	for i := 0; i < n; i++ {
		v := vals[i%len(vals)]
		fmt.Fprintf(&b, "%s,dept%d\n", v, i)
		labels = append(labels, Label{
			Line: i + 2, Value: v, Types: []string{"SSN"}, MinBand: BandLow,
		})
	}
	return Case{
		Name:       fmt.Sprintf("growth_%d", n),
		Origin:     "generated by growthCase (timing_test.go)",
		Rationale:  "synthetic scaling probe, not part of the scored corpus",
		Checks:     []string{"SSN"},
		Input:      b.String(),
		Labels:     labels,
		Redactable: true,
	}
}

// TestScorerScalesLinearly — the gate itself must not be the bottleneck.
//
// Asserts on MATCH COUNT growth rather than wall clock: the scorer's work is
// proportional to labels x candidate matches, so if that product grows quadratically
// the count reveals it deterministically, with zero timing variance.
func TestScorerScalesLinearly(t *testing.T) {
	cfg := mustPureConfig(t)

	type row struct {
		n     int
		tp    int
		ratio float64
	}
	var rows []row
	prev := 0

	for _, n := range []int{125, 250, 500, 1000, 2000} {
		c := growthCase(n)
		out, misses, _, err := ScoreCase(c, cfg)
		if err != nil {
			t.Fatalf("n=%d: %v", n, err)
		}

		// Vacuity floor: if the generator stops producing findings, the "linear"
		// result below is meaningless. This is exactly how 3 of the repo's existing
		// complexity targets silently measured nothing.
		if out.TP != n {
			t.Fatalf("n=%d: scored %d TP, want %d (%d missed). The scaling probe must "+
				"actually match every label, or the growth measurement is vacuous.\nfirst miss: %s",
				n, out.TP, n, out.FNMissed, firstOr(misses, "none"))
		}

		r := 0.0
		if prev > 0 {
			r = float64(out.TP) / float64(prev)
		}
		rows = append(rows, row{n, out.TP, r})
		prev = out.TP
	}

	for _, r := range rows {
		if r.ratio == 0 {
			t.Logf("  n=%-5d TP=%-5d (baseline)", r.n, r.tp)
			continue
		}
		t.Logf("  n=%-5d TP=%-5d %.2fx per doubling", r.n, r.tp, r.ratio)
		// Linear means ~2.0x per doubling. Quadratic would be ~4.0x. The 3.0
		// threshold sits between them with room for the +1 header row.
		if r.ratio > 3.0 {
			t.Errorf("n=%d: work grew %.2fx on a doubling of input; linear is ~2.0x and "+
				"quadratic is ~4.0x. A slow gate gets deleted.", r.n, r.ratio)
		}
	}
}

// TestCorpusRunsInReasonableTime is a smoke check, not a gate.
//
// It logs the per-layer cost so a PR body can quote it, and only fails on an
// absurd regression (a 60s budget against a measured ~5s), because a tight
// wall-clock bound on shared CI hardware is a flake, not a signal.
func TestCorpusRunsInReasonableTime(t *testing.T) {
	if testing.Short() {
		t.Skip("timing smoke check; skipped under -short")
	}

	report := map[string]float64{}

	report["validator"] = secondsOf(t, func() {
		if _, err := Score(); err != nil {
			t.Fatalf("Score: %v", err)
		}
	})
	for _, st := range sinkStrategies {
		report["redaction/"+st] = secondsOf(t, func() {
			if _, err := ScoreSink(st, t.TempDir()); err != nil {
				t.Fatalf("ScoreSink(%s): %v", st, err)
			}
		})
	}
	report["suppression"] = secondsOf(t, func() {
		if _, err := ScoreSuppression(t.TempDir()); err != nil {
			t.Fatalf("ScoreSuppression: %v", err)
		}
	})

	total := 0.0
	for _, k := range []string{"validator", "redaction/simple", "redaction/format_preserving", "suppression"} {
		t.Logf("  %-28s %6.2fs", k, report[k])
		total += report[k]
	}
	t.Logf("  %-28s %6.2fs", "TOTAL (in-process layers)", total)

	const budget = 60.0
	if total > budget {
		t.Errorf("the whole corpus took %.1fs, over the %.0fs budget. `make score` has to "+
			"be cheap enough to run on every change or it will not be run at all.", total, budget)
	}
}

// helpers kept at the bottom so the intent above reads first.

func mustPureConfig(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.LoadConfig("")
	if err != nil {
		t.Fatalf("LoadConfig: %v", err)
	}
	return cfg
}

func secondsOf(t *testing.T, fn func()) float64 {
	t.Helper()
	start := time.Now()
	fn()
	return time.Since(start).Seconds()
}

func firstOr(list []string, fallback string) string {
	if len(list) == 0 {
		return fallback
	}
	return list[0]
}
