// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package personname

// technicalAdjectivesMap for O(1) lookups of technical adjectives
var technicalAdjectivesMap = map[string]bool{
	"manual":      true,
	"automatic":   true,
	"automated":   true,
	"primary":     true,
	"secondary":   true,
	"backup":      true,
	"test":        true,
	"production":  true,
	"staging":     true,
	"development": true,
	"local":       true,
	"remote":      true,
	"public":      true,
	"private":     true,
	"internal":    true,
	"external":    true,
	"global":      true,
	"regional":    true,
	"cross":       true,
	"multi":       true,
	"single":      true,
	"dual":        true,
	"max":         true,
	"min":         true,
	"bulk":        true,
	"batch":       true,
}

// technicalNounsMap for O(1) lookups of technical nouns
var technicalNounsMap = map[string]bool{
	"execution":      true,
	"deployment":     true,
	"testing":        true,
	"configuration":  true,
	"management":     true,
	"operations":     true,
	"monitoring":     true,
	"logging":        true,
	"auditing":       true,
	"validation":     true,
	"verification":   true,
	"processing":     true,
	"handling":       true,
	"control":        true,
	"access":         true,
	"security":       true,
	"authentication": true,
	"authorization":  true,
	"key":            true,
	"keys":           true,
	"session":        true,
	"connection":     true,
	"transaction":    true,
	"query":          true,
	"request":        true,
	"response":       true,
	"event":          true,
	"message":        true,
	"notification":   true,
	"alert":          true,
	"error":          true,
	"exception":      true,
	"failure":        true,
	"timeout":        true,
	"service":        true,
	"component":      true,
	"module":         true,
	"function":       true,
	"method":         true,
	"procedure":      true,
	"algorithm":      true,
	"pattern":        true,
	"template":       true,
	"schema":         true,
	"model":          true,
}

// technicalTermsMap consolidates all technical terms, business patterns, and common phrases for O(1) lookups
var technicalTermsMap = map[string]bool{
	// Multi-word technical phrases
	"manual execution":                true,
	"test cross":                      true,
	"primary key":                     true,
	"max concurrency":                 true,
	"max errors":                      true,
	"manual testing":                  true,
	"manual deployment":               true,
	"manual operations":               true,
	"manual intervention":             true,
	"manual member":                   true,
	"manual executions":               true,
	"bulk cross":                      true,
	"centralized logging":             true,
	"use case":                        true,
	"test case":                       true,
	"cross account":                   true,
	"member account":                  true,
	"logging account":                 true,
	"management account":              true,
	"current account":                 true,
	"target account":                  true,
	"administrator account":           true,
	"delegated administrator account": true,
	"manual execution auditor":        true,
	"member account execution role":   true,
	"member account validation":       true,
	"manual member account setup":     true,
	"manual member account":           true,
	"resource groups":                 true,
	"git repository":                  true,
	"git repo":                        true,
	"customer log":                    true,
	"customer audit":                  true,
	"log archive":                     true,
	"customer log archive":            true,
	"member accounts":                 true,
	"logging accounts":                true,
	"target host":                     true,
	"output name":                     true,
	"current value":                   true,
	"document name":                   true,
	"trust role":                      true,
	"dry run":                         true,
	"authorization tracking":          true,
	"critical security":               true,
	"account structure":               true,
	"validation dashboard":            true,
	"verify environment":              true,
	"delegated administrator":         true,
	"execution role":                  true,
	"account validation":              true,
	"environment validation":          true,
	"security validation":             true,
	"structure validation":            true,
	"run validation":                  true,
	"dry run v":                       true,
	"critical security v":             true,
	"account structure v":             true,
	"verify environment v":            true,
	"auto scaling":                    true,
	"load balancer":                   true,
	"api gateway":                     true,
	"lambda function":                 true,
	"cloud formation":                 true,
	"machine learning":                true,
	"artificial intelligence":         true,
	"data science":                    true,
	"big data":                        true,
	"software engineering":            true,
	"system administration":           true,
	"network security":                true,
	"database management":             true,
	"web development":                 true,
	"mobile development":              true,
	"quality assurance":               true,
	"user interface":                  true,
	"user experience":                 true,
	"business logic":                  true,
	"version control":                 true,
	"continuous integration":          true,
	"continuous deployment":           true,
	"infrastructure code":             true,
	"configuration management":        true,
	"monitoring system":               true,
	"logging framework":               true,
	"testing framework":               true,
	"development environment":         true,
	"production environment":          true,
	"staging environment":             true,
	"file system":                     true,
	"operating system":                true,
	"command line":                    true,
	"graphical interface":             true,
	"network protocol":                true,
	"security protocol":               true,
	"authentication system":           true,
	"authorization system":            true,
	"access control":                  true,
	"permission system":               true,
	"backup system":                   true,
	"recovery system":                 true,
	"disaster recovery":               true,
	"project management":              true,
	"task management":                 true,
	"resource management":             true,
	"change management":               true,
	"release management":              true,
	"incident management":             true,

	// Business and corporate terms - reference businessPatternsMap to avoid duplication
	// Keeping only terms unique to technical contexts

	// Single word technical terms (consolidated from technicalNounsMap)
	"execution":      true,
	"deployment":     true,
	"testing":        true,
	"configuration":  true,
	"management":     true,
	"operations":     true,
	"monitoring":     true,
	"logging":        true,
	"auditing":       true,
	"validation":     true,
	"verification":   true,
	"processing":     true,
	"handling":       true,
	"control":        true,
	"access":         true,
	"security":       true,
	"authentication": true,
	"authorization":  true,
	"key":            true,
	"keys":           true,
	"session":        true,
	"connection":     true,
	"transaction":    true,
	"query":          true,
	"request":        true,
	"response":       true,
	"event":          true,
	"message":        true,
	"notification":   true,
	"alert":          true,
	"error":          true,
	"exception":      true,
	"failure":        true,
	"timeout":        true,
	"service":        true,
	"component":      true,
	"module":         true,
	"function":       true,
	"method":         true,
	"procedure":      true,
	"algorithm":      true,
	"pattern":        true,
	"template":       true,
	"schema":         true,
	"model":          true,
}

// veryCommonNamesMap for O(1) lookups of very common names that often appear in technical contexts
// Only includes terms unique to this map (duplicates with other maps removed)
var veryCommonNamesMap = map[string]bool{
	"use":       true,
	"case":      true,
	"admin":     true,
	"user":      true,
	"guest":     true,
	"default":   true,
	"system":    true,
	"main":      true,
	"root":      true,
	"temp":      true,
	"temporary": true,
	"example":   true,
	"sample":    true,
	"demo":      true,
	"trial":     true,
	"beta":      true,
	"alpha":     true,
	"dev":       true,
	"prod":      true,
	"install":   true,
	"update":    true,
	"upgrade":   true,
	"fix":       true,
	"bug":       true,
	"issue":     true,
	"warning":   true,
	"info":      true,
	"debug":     true,
	"trace":     true,
	"check":     true,
	"confirm":   true,
	"approve":   true,
	"reject":    true,
	"cancel":    true,
	"abort":     true,
	"stop":      true,
	"start":     true,
	"run":       true,
	"operate":   true,
}

// emailPatternsMap for efficient email context analysis
var emailPatternsMap = map[string]bool{
	"from:":        true,
	"to:":          true,
	"cc:":          true,
	"sent by":      true,
	"regards":      true,
	"sincerely":    true,
	"best regards": true,
	"kind regards": true,
}

var businessPatternsMap = map[string]bool{
	"inc":             true,
	"llc":             true,
	"ltd":             true,
	"corp":            true,
	"corporation":     true,
	"company":         true,
	"enterprises":     true,
	"industries":      true,
	"manufacturing":   true,
	"consulting":      true,
	"group":           true,
	"associates":      true,
	"catalog":         true,
	"product":         true,
	"brand":           true,
	"version":         true,
	"series":          true,
	"interface":       true,
	"auditor":         true,
	"manager":         true,
	"troubleshooting": true,
	"guide":           true,
	"documentation":   true,
	"readme":          true,
	"installation":    true,
	"setup":           true,
	"config":          true,
	"script":          true,
	"automation":      true,
	"parameters":      true,
	"concurrency":     true,
	"errors":          true,
	"intervention":    true,
	"required":        true,
	"table":           true,
	"database":        true,
	"cross-account":   true,
	"stackset":        true,
	"resource":        true,
	"groups":          true,
	"patch":           true,
	"ansible":         true,
	"aws":             true,
	"ssm":             true,
	"ec2":             true,
	"s3":              true,
	"lambda":          true,
	"cloudformation":  true,
	"terraform":       true,
}

var productPatternsMap = map[string]bool{
	"air":      true,
	"tennis":   true,
	"baby":     true,
	"golf":     true,
	"made":     true,
	"racket":   true,
	"shampoo":  true,
	"clubs":    true,
	"nike":     true,
	"samsung":  true,
	"ford":     true,
	"galaxy":   true,
	"explorer": true,
	"firearm":  true,
	"weapon":   true,
}

var geoPatternsMap = map[string]bool{
	"city":      true,
	"county":    true,
	"state":     true,
	"mountain":  true,
	"lake":      true,
	"river":     true,
	"creek":     true,
	"valley":    true,
	"park":      true,
	"street":    true,
	"avenue":    true,
	"road":      true,
	"drive":     true,
	"boulevard": true,
}
