# Simple Ferret Scan GitHub Actions Workflow
# Basic sensitive data detection for pull requests

name: Security Scan

on:
  pull_request:
    branches: [main, master]

jobs:
  scan:
    name: Ferret Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.1"

      - name: Build and run Ferret Scan
        run: |
          # Build ferret-scan
          make build

          # Get changed files
          git diff --name-only --diff-filter=ACM \
            ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
            | grep -E '\.(py|js|ts|go|java|json|yaml|yml|env)$' \
            | grep -v -E '(test_|_test\.|spec_|_spec\.)' \
            > changed_files.txt || true

          # Scan changed files
          if [ -s changed_files.txt ]; then
            echo "🔍 Scanning changed files..."
            while read -r file; do
              if [ -f "$file" ]; then
                echo "Scanning: $file"
                ./bin/ferret-scan --file "$file" --confidence high --no-color --quiet
              fi
            done < changed_files.txt
          else
            echo "✅ No relevant files to scan"
          fi
